name: Validate Pull Request Changes

# most important for us is "synchronize" event for pull request, which is included by default
on: pull_request

jobs:
  lint:
    name: Lint Python code
    uses: ./.github/workflows/step_lint.yaml

  unit_tests:
    name: Run unit tests
    uses: ./.github/workflows/step_test_from_dir.yaml
    with:
      target: tests/unit
      description: Unit

  integration_tests:
    name: Run integration tests
    uses: ./.github/workflows/step_test_from_dir.yaml
    with:
      target: tests/integration
      description: Integration
